baseURL : https://hmble.dev 
languageCode : en-in
title : hmbledev blog by Samyak
description: A blog for those who want to read programming content in English
DefaultContentLanguage : en-in
enableRobotsTXT: true
canonifyURLs: true
googleAnalytics: G-K1HYKY4MFT

pygmentsUseClasses: true
sitename: hmbledev
paginate: 10
github: hmble
twitter: hmbledev
author: Samyak Bakliwal
themecolor: "#D53F8C"

services:
  rss:
    limit: 15
markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: English
    weight: 2
  en-in:
    languageName: Hinglish
    weight: 1


taxonomies:
  tag: tags
  series: series
