baseURL : http://example.org/
languageCode : en-in
title : hmbledev blog by Samyak
DefaultContentLanguage : en-in

languages:
  en:
    languageName: English
    weight: 2
  en-in:
    languageName: Hinglish
    weight: 1


taxonomies:
  tag: tags
  series: series
